org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStore=C:\\Users\\User\\.gradle\\gradle-truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
systemProp.javax.net.ssl.trustStore=C:\\Users\\User\\.gradle\\gradle-truststore.jks
systemProp.javax.net.ssl.trustStorePassword=changeit
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
