export const ASSIGNMENT_TIMEOUT_MS = 5 * 60 * 1000;
export const RESERVATION_ACTIVATION_HOUR = 5;
export const RESERVATION_ACTIVATION_TIMEZONE = "Europe/Lisbon";
export const AVERAGE_SPEED_KMH = 35;
export const MIN_RESERVATION_WINDOW_MINUTES = 15;
export const DRIVER_HEARTBEAT_STALE_MS = 3 * 60 * 1000;
export const DRIVER_LOCATION_STALE_MS = 60 * 1000;
export const DEFAULT_DEBT_LIMIT_CENTS = -2000;
export const OPERATION_CURRENCY_CODE = "EUR";
export const JOB_LOCK_TTL_DAYS = 7;
export const TRIP_EVENT_TTL_DAYS = 90;
export const FCM_TOKEN_CLEANUP_BATCH_SIZE = 300;
export const TRIP_EXTENSION_WINDOW_MS = 60 * 1000;
export const DRIVER_CANDIDATE_RADIUS_KM = 12;
export const MAX_DRIVER_CANDIDATES = 30;
export const MIN_REMINDER_OFFSET_MINUTES = 1;
export const MAX_REMINDER_OFFSET_WRITE_MINUTES = 60;
export const MAX_REMINDER_OFFSET_LEGACY_READ_MINUTES = 180;
export const MAX_REMINDER_OFFSETS_PER_ENTITY = 5;
export const DEFAULT_EVENT_REMINDER_OFFSET_MINUTES = 15;
export const DEFAULT_RESERVATION_REMINDER_OFFSET_MINUTES = 30;

const CALLABLE_REGION = "europe-southwest1" as const;
const CALLABLE_CONCURRENCY = 40 as const;

export const CRITICAL_CALLABLE_RUNTIME_OPTIONS = {
  region: CALLABLE_REGION,
  minInstances: 0,
  concurrency: CALLABLE_CONCURRENCY,
  invoker: "public",
} as const;

export const STANDARD_CALLABLE_RUNTIME_OPTIONS = {
  region: CALLABLE_REGION,
  minInstances: 0,
  concurrency: CALLABLE_CONCURRENCY,
  invoker: "public",
} as const;

export const CALLABLE_RUNTIME_OPTIONS = CRITICAL_CALLABLE_RUNTIME_OPTIONS;

export const INACTIVE_TRIP_STATUSES = new Set([
  "COMPLETED",
  "CHARGE_APPLIED",
  "CANCELLED_BY_CLIENT",
  "CANCELLED_BY_DRIVER",
  "NO_SHOW",
  "NO_DRIVERS_AVAILABLE",
]);

export const VALID_TRIP_STATUSES = new Set([
  "REQUESTED",
  "DRIVER_ASSIGNED_WAITING_ACCEPTANCE",
  "DRIVER_ACCEPTED",
  "DRIVER_DECLINED",
  "NO_DRIVERS_AVAILABLE",
  "DRIVER_EN_ROUTE",
  "DRIVER_ARRIVED",
  "IN_TRIP",
  "ARRIVED_DESTINATION",
  "EXTENSION_WINDOW",
  "COMPLETED",
  "CHARGE_APPLIED",
  "CANCELLED_BY_CLIENT",
  "CANCELLED_BY_DRIVER",
  "NO_SHOW",
]);

export const AVAILABILITY_RESTORE_TRIP_STATUSES = new Set([
  "CANCELLED_BY_CLIENT",
  "CANCELLED_BY_DRIVER",
  "NO_SHOW",
  "COMPLETED",
  "CHARGE_APPLIED",
]);

export const ACTIVE_RESERVATION_STATUSES = ["scheduled", "pending", "confirmed"];

export const DRIVER_STATUS_COLLECTION = "driverStatus";
export const DRIVER_LOCATION_PATH = "driverLocations";
export const DRIVER_LOCATION_GEOHASH_FIELD = "g";
export const DRIVER_LOCATION_COORDS_FIELD = "l";
