import json
import re
from pathlib import Path

strings = {
    "appNameLocalTransport": ("Local Transport", "Local Transport", "Local Transport"),
    "signIn": ("Entrar", "Sign in", "Iniciar sesión"),
    "cancel": ("Cancelar", "Cancel", "Cancelar"),
    "signOut": ("Sair", "Sign out", "Salir"),
    "signOutTitle": ("Terminar sessão", "End session", "Cerrar sesión"),
    "signOutConfirmMessage": (
        "Tem a certeza de que pretende sair da sua conta?",
        "Are you sure you want to sign out of your account?",
        "¿Seguro que desea salir de su cuenta?",
    ),
    "signOutFailed": (
        "Não foi possível terminar sessão. Tente novamente.",
        "Could not sign out. Please try again.",
        "No se pudo cerrar la sesión. Inténtelo de nuevo.",
    ),
    "tryAgain": ("Tentar novamente", "Try again", "Intentar de nuevo"),
    "featureComingSoon": (
        "{feature} estará disponível em breve.",
        "{feature} will be available soon.",
        "{feature} estará disponible pronto.",
    ),
    "navHome": ("Início", "Home", "Inicio"),
    "navTrips": ("Viagens", "Trips", "Viajes"),
    "navReservations": ("Reservas", "Reservations", "Reservas"),
    "navProfile": ("Perfil", "Profile", "Perfil"),
    "loginSubtitle": (
        "Inicie sessão para gerir as suas viagens.",
        "Sign in to manage your trips.",
        "Inicie sesión para gestionar sus viajes.",
    ),
    "loginSettingsTooltip": ("Definições", "Settings", "Ajustes"),
    "loginEmailOrMobileLabel": ("E-mail ou Telemóvel", "Email or mobile", "Correo o móvil"),
    "loginEmailHint": ("ex: joao@email.com", "e.g. joao@email.com", "ej.: joao@email.com"),
    "loginPasswordLabel": ("Palavra-passe", "Password", "Contraseña"),
    "loginForgotPassword": ("Esqueceu-se?", "Forgot?", "¿Olvidó?"),
    "loginFillEmailPassword": (
        "Preencha o e-mail e a palavra-passe.",
        "Enter email and password.",
        "Introduzca correo y contraseña.",
    ),
    "loginNoAccountPrompt": (
        "Ainda não tem conta? ",
        "Don't have an account yet? ",
        "¿Aún no tiene cuenta? ",
    ),
    "loginRegisterNow": ("Registar agora", "Register now", "Registrarse ahora"),
    "loginPrivacy": ("Privacidade", "Privacy", "Privacidad"),
    "loginTermsOfUse": ("Termos de Uso", "Terms of use", "Términos de uso"),
    "loginSupport": ("Suporte", "Support", "Soporte"),
    "loginRoleClient": ("Cliente", "Client", "Cliente"),
    "loginRoleProfessional": ("Profissional", "Professional", "Profesional"),
    "secureConnectionE2E": (
        "Ligação segura e encriptada ponta-a-ponta.",
        "Secure end-to-end encrypted connection.",
        "Conexión segura cifrada de extremo a extremo.",
    ),
    "authErrorUnexpected": (
        "Ocorreu um erro inesperado. Tente novamente.",
        "An unexpected error occurred. Please try again.",
        "Ocurrió un error inesperado. Inténtelo de nuevo.",
    ),
    "authErrorProfileNotFound": (
        "Perfil de utilizador não encontrado.",
        "User profile not found.",
        "Perfil de usuario no encontrado.",
    ),
    "authErrorAccountInactive": (
        "Esta conta está inactiva. Contacte o suporte.",
        "This account is inactive. Contact support.",
        "Esta cuenta está inactiva. Contacte con soporte.",
    ),
    "authErrorRoleMismatch": (
        "Perfil não corresponde ao tipo selecionado.",
        "Profile does not match the selected type.",
        "El perfil no coincide con el tipo seleccionado.",
    ),
    "authErrorInvalidEmail": ("E-mail inválido.", "Invalid email.", "Correo no válido."),
    "authErrorUserDisabled": (
        "Esta conta está desactivada.",
        "This account is disabled.",
        "Esta cuenta está desactivada.",
    ),
    "authErrorWrongCredentials": (
        "E-mail ou palavra-passe incorrectos.",
        "Incorrect email or password.",
        "Correo o contraseña incorrectos.",
    ),
    "authErrorTooManyRequests": (
        "Demasiadas tentativas. Tente mais tarde.",
        "Too many attempts. Try again later.",
        "Demasiados intentos. Inténtelo más tarde.",
    ),
    "authErrorSignInFailed": (
        "Não foi possível iniciar sessão. Tente novamente.",
        "Could not sign in. Please try again.",
        "No se pudo iniciar sesión. Inténtelo de nuevo.",
    ),
    "settingsTitle": ("Definições", "Settings", "Ajustes"),
    "settingsSubtitle": (
        "Ajuste preferências e mantenha a aplicação pronta para si.",
        "Adjust preferences and keep the app ready for you.",
        "Ajuste preferencias y mantenga la app lista para usted.",
    ),
    "settingsLanguage": ("Idioma", "Language", "Idioma"),
    "settingsLanguageDescription": (
        "Escolha o idioma da aplicação. Pode repor o idioma do dispositivo a qualquer momento.",
        "Choose the app language. You can reset to the device language at any time.",
        "Elija el idioma de la aplicación. Puede restablecer el idioma del dispositivo en cualquier momento.",
    ),
    "settingsLanguageEnglish": ("English", "English", "English"),
    "settingsLanguageSpanish": ("Español", "Spanish", "Español"),
    "settingsLanguagePortuguese": (
        "Português (Portugal)",
        "Portuguese (Portugal)",
        "Portugués (Portugal)",
    ),
    "settingsLanguageFollowingDevice": (
        "A seguir o idioma do dispositivo ({language}).",
        "Following device language ({language}).",
        "Siguiendo el idioma del dispositivo ({language}).",
    ),
    "settingsLanguageManual": (
        "Idioma selecionado manualmente: {language}.",
        "Language selected manually: {language}.",
        "Idioma seleccionado manualmente: {language}.",
    ),
    "settingsLanguageResetSnack": (
        "Idioma reposto para o do dispositivo.",
        "Language reset to device default.",
        "Idioma restablecido al del dispositivo.",
    ),
    "settingsUseDeviceLanguage": (
        "Repor idioma do dispositivo",
        "Reset to device language",
        "Restablecer idioma del dispositivo",
    ),
    "settingsDisplayCurrency": (
        "Moeda de visualização",
        "Display currency",
        "Moneda de visualización",
    ),
    "settingsDisplayCurrencyDescription": (
        "Escolha a moeda em que pretende ver os valores na aplicação.",
        "Choose which currency you want to see values in throughout the app.",
        "Elija la moneda en la que desea ver los importes en toda la aplicación.",
    ),
    "settingsCurrencyCve": (
        "Escudo cabo-verdiano (CVE)",
        "Cape Verdean escudo (CVE)",
        "Escudo caboverdiano (CVE)",
    ),
    "settingsCurrencyEur": ("Euro (€)", "Euro (€)", "Euro (€)"),
    "settingsCurrencyUsd": ("Dólar americano (USD)", "US dollar (USD)", "Dólar estadounidense (USD)"),
    "settingsAccountSection": ("Conta", "Account", "Cuenta"),
    "settingsChangePassword": ("Alterar palavra-passe", "Change password", "Cambiar contraseña"),
    "settingsSignOutAction": ("Terminar sessão", "Sign out", "Cerrar sesión"),
    "settingsSignOutLoading": ("A terminar sessão...", "Signing out...", "Cerrando sesión..."),
    "settingsDeveloperSection": (
        "Ferramentas de desenvolvedor",
        "Developer tools",
        "Herramientas de desarrollador",
    ),
    "settingsDriverLocationSimulationTitle": (
        "Simulação de localização (demo)",
        "Location simulation (demo)",
        "Simulación de ubicación (demo)",
    ),
    "settingsDriverLocationSimulationDescription": (
        "Disponível apenas em builds de desenvolvimento. No dispositivo do motorista, publica movimento simulado em direção à recolha na viagem ativa, sem marcar chegada automaticamente.",
        "Available only in development builds. On the driver device, publishes simulated movement toward pickup on the active trip, without marking arrival automatically.",
        "Disponible solo en compilaciones de desarrollo. En el dispositivo del conductor, publica movimiento simulado hacia la recogida en el viaje activo, sin marcar llegada automáticamente.",
    ),
    "settingsDriverLocationSimulationSwitchLabel": (
        "Simular movimento do motorista",
        "Simulate driver movement",
        "Simular movimiento del conductor",
    ),
    "settingsResetOnboarding": (
        "Repor onboarding",
        "Reset onboarding",
        "Restablecer onboarding",
    ),
    "settingsResetDone": (
        "Onboarding reposto.",
        "Onboarding reset.",
        "Onboarding restablecido.",
    ),
    "settingsDeveloperDebugOnly": (
        "Secção visível apenas em builds de debug.",
        "Section visible only in debug builds.",
        "Sección visible solo en compilaciones de depuración.",
    ),
    "profileTitle": ("Perfil", "Profile", "Perfil"),
    "profileDefaultUserName": ("Utilizador", "User", "Usuario"),
    "profileSessionNotFound": (
        "Sessão não encontrada. Inicie sessão novamente.",
        "Session not found. Please sign in again.",
        "Sesión no encontrada. Inicie sesión de nuevo.",
    ),
    "profileLoadFailed": (
        "Não foi possível carregar o perfil. Tente novamente.",
        "Could not load profile. Please try again.",
        "No se pudo cargar el perfil. Inténtelo de nuevo.",
    ),
    "profileRoleClient": ("Utilizador", "User", "Usuario"),
    "profileRoleDriver": ("Motorista", "Driver", "Conductor"),
    "profileRoleAdmin": ("Administrador", "Administrator", "Administrador"),
    "profilePhone": ("Telefone", "Phone", "Teléfono"),
    "profilePhoneNotSet": ("Não definido", "Not set", "No definido"),
    "profileAccountType": ("Tipo de conta", "Account type", "Tipo de cuenta"),
    "profileStatus": ("Estado", "Status", "Estado"),
    "profileStatusActive": ("Activa", "Active", "Activa"),
    "profileStatusInactive": ("Inactiva", "Inactive", "Inactiva"),
    "profileMenuSettings": ("Definições", "Settings", "Ajustes"),
    "profileMenuPaymentMethods": ("Métodos de pagamento", "Payment methods", "Métodos de pago"),
    "profileMenuHelpCenter": ("Centro de ajuda", "Help center", "Centro de ayuda"),
    "profileMenuPrivacySecurity": (
        "Privacidade e segurança",
        "Privacy and security",
        "Privacidad y seguridad",
    ),
    "profileSessionSection": ("Sessão", "Session", "Sesión"),
    "profileGoToLogin": ("Ir para o login", "Go to login", "Ir al inicio de sesión"),
    "homeAvailableBalance": ("Saldo Disponível", "Available balance", "Saldo disponible"),
    "homeTopUp": ("Carregar", "Top up", "Recargar"),
    "homeActionRequest": ("Pedir", "Request", "Pedir"),
    "homeActionBook": ("Reservar", "Book", "Reservar"),
    "homeActionRent": ("Alugar", "Rent", "Alquilar"),
    "homeActionHistory": ("Histórico", "History", "Historial"),
    "homeActionBalance": ("Saldo", "Balance", "Saldo"),
    "homeWhereToday": ("Para onde vamos hoje?", "Where are we going today?", "¿Adónde vamos hoy?"),
    "homeCurrentLocation": ("Localização Atual", "Current location", "Ubicación actual"),
    "homeDestination": ("Destino", "Destination", "Destino"),
    "homeDestinationHint": ("Para onde deseja ir?", "Where do you want to go?", "¿Adónde desea ir?"),
    "homeConfirmRoute": ("Confirmar Trajeto", "Confirm route", "Confirmar trayecto"),
    "reservationsTitle": ("Reservas", "Reservations", "Reservas"),
    "reservationsSubtitle": (
        "Gerencie as suas próximas viagens",
        "Manage your upcoming trips",
        "Gestione sus próximos viajes",
    ),
    "reservationsNew": ("Nova reserva", "New reservation", "Nueva reserva"),
    "reservationsPickup": ("Recolha", "Pickup", "Recogida"),
    "reservationsDestination": ("Destino", "Destination", "Destino"),
    "reservationsDetails": ("Detalhes", "Details", "Detalles"),
    "reservationsCancel": ("Cancelar", "Cancel", "Cancelar"),
    "reservationsStatusConfirmed": ("Confirmada", "Confirmed", "Confirmada"),
    "reservationsStatusPending": ("Pendente", "Pending", "Pendiente"),
    "tripHistoryTitle": ("Histórico de Viagens", "Trip history", "Historial de viajes"),
    "tripHistoryDetails": ("Detalhes", "Details", "Detalles"),
    "tripDetailsSummary": ("Resumo da Viagem", "Trip summary", "Resumen del viaje"),
    "tripDetailsStatusCompleted": ("Concluída", "Completed", "Completada"),
    "rentalTitle": ("Aluguer de Veículos", "Vehicle rental", "Alquiler de vehículos"),
    "rentalSubtitle": (
        "Encontre o parceiro perfeito para a sua próxima viagem.",
        "Find the perfect partner for your next trip.",
        "Encuentre el socio perfecto para su próximo viaje.",
    ),
    "rentalSearchAvailable": (
        "Pesquisar Veículos Disponíveis",
        "Search available vehicles",
        "Buscar vehículos disponibles",
    ),
    "driverSearchTitle": (
        "A procurar motorista disponível",
        "Looking for an available driver",
        "Buscando conductor disponible",
    ),
    "driverFoundTitle": ("Motorista encontrado", "Driver found", "Conductor encontrado"),
    "driverEnRouteStatus": ("Motorista a caminho", "Driver on the way", "Conductor en camino"),
    "tripInProgressEndTrip": ("Terminar Viagem", "End trip", "Finalizar viaje"),
    "tripInProgressSupport": ("Suporte", "Support", "Soporte"),
    "tripCompletedTitle": ("Viagem Concluída!", "Trip completed!", "¡Viaje completado!"),
    "tripCompletedBackHome": ("Voltar ao início", "Back to home", "Volver al inicio"),
    "premiumHomeOrderNow": ("Pedir agora", "Order now", "Pedir ahora"),
    "support": ("Suporte", "Support", "Soporte"),
    "destination": ("Destino", "Destination", "Destino"),
    "details": ("Detalhes", "Details", "Detalles"),
    "premiumMobility": ("Mobilidade Premium", "Premium Mobility", "Movilidad Premium"),
    "seeAll": ("Ver todos", "See all", "Ver todos"),
    "edit": ("Editar", "Edit", "Editar"),
    "total": ("Total", "Total", "Total"),
    "subtotal": ("Subtotal", "Subtotal", "Subtotal"),
    "quantity": ("Quantidade", "Quantity", "Cantidad"),
    "distance": ("Distância", "Distance", "Distancia"),
    "duration": ("Duração", "Duration", "Duración"),
    "premium": ("Premium", "Premium", "Premium"),
    "newBadge": ("Novo", "New", "Nuevo"),
    "promotion": ("Promoção", "Promotion", "Promoción"),
    "free": ("Grátis", "Free", "Gratis"),
    "live": ("LIVE", "LIVE", "LIVE"),
    "verified": ("Verificado", "Verified", "Verificado"),
    "createAccount": ("Criar conta", "Create account", "Crear cuenta"),
    "splashSecureConnection": (
        "Conexão Segura & Encriptada",
        "Secure & Encrypted Connection",
        "Conexión segura y cifrada",
    ),
    "splashExecutiveBadge": ("EXECUTIVO", "EXECUTIVE", "EJECUTIVO"),
    "splashHeroTitle": (
        "O seu tempo,\nvalorizado.",
        "Your time,\nvalued.",
        "Su tiempo,\nvalorado.",
    ),
    "splashHeroSubtitle": (
        "Transporte personalizado com conforto e pontualidade.",
        "Personalized transport with comfort and punctuality.",
        "Transporte personalizado con confort y puntualidad.",
    ),
    "splashInstantBookingTitle": ("Reservas Instantâneas", "Instant Bookings", "Reservas instantáneas"),
    "splashInstantBookingSubtitle": (
        "Planeie a sua viagem em segundos com a nossa rede exclusiva.",
        "Plan your trip in seconds with our exclusive network.",
        "Planifique su viaje en segundos con nuestra red exclusiva.",
    ),
    "splashDriverOfToday": ("MOTORISTA DE HOJE", "TODAY'S DRIVER", "CONDUCTOR DE HOY"),
    "adminAppBarTitle": ("Mobilidade Premium", "Premium Mobility", "Movilidad Premium"),
    "adminFleetStatusTitle": ("Estado da Frota", "Fleet Status", "Estado de la flota"),
    "adminFleetStatusUpdated": ("Atualizado: Agora", "Updated: Now", "Actualizado: Ahora"),
    "adminActiveTripsLabel": ("Viagens Ativas", "Active Trips", "Viajes activos"),
    "adminActiveTripsTrend": ("+12% vs. ontem", "+12% vs. yesterday", "+12% vs. ayer"),
    "adminAvailableDriversLabel": ("Motoristas Disponíveis", "Available Drivers", "Conductores disponibles"),
    "adminAvailableDriversHint": ("Pronto para despacho", "Ready for dispatch", "Listo para despacho"),
    "adminCriticalOpsTitle": ("Operações Críticas", "Critical Operations", "Operaciones críticas"),
    "adminPendingDebtorsTitle": ("Devedores Pendentes", "Pending Debtors", "Deudores pendientes"),
    "adminPendingDebtorsSubtitle": ("3 faturas em atraso", "3 overdue invoices", "3 facturas vencidas"),
    "adminMonthlyReportsTitle": ("Relatórios Mensais", "Monthly Reports", "Informes mensuales"),
    "adminMonthlyReportsSubtitle": ("Performance de Outubro", "October performance", "Rendimiento de octubre"),
    "adminActivityMapTitle": ("Mapa de Atividade", "Activity Map", "Mapa de actividad"),
    "adminRatesTitle": ("Tarifas & Mercado", "Rates & Market", "Tarifas y mercado"),
    "adminBaseRateLabel": ("Tarifa Base", "Base Rate", "Tarifa base"),
    "adminBaseRateDynamic": ("Dinâmica: Ativa (1.2x)", "Dynamic: Active (1.2x)", "Dinámica: Activa (1.2x)"),
    "adminFuelCostLabel": ("Custo Combustível", "Fuel Cost", "Costo combustible"),
    "adminFuelCostHint": ("Média Nacional", "National Average", "Media nacional"),
    "adminRecentFleetTitle": ("Frota Recente", "Recent Fleet", "Flota reciente"),
    "adminFleetStatusOnTrip": ("Em Viagem", "On Trip", "En viaje"),
    "adminFleetStatusInactive": ("Inativo", "Inactive", "Inactivo"),
    "adminFleetDriverPrefix": ("Motorista: {name}", "Driver: {name}", "Conductor: {name}"),
    "deliveryDeliverTo": (
        "Entregar em: Av. da Liberdade, Lisboa",
        "Deliver to: Av. da Liberdade, Lisbon",
        "Entregar en: Av. da Liberdade, Lisboa",
    ),
    "deliverySearchHint": ("O que procura hoje?", "What are you looking for today?", "¿Qué busca hoy?"),
    "deliveryExploreCategories": ("Explorar Categorias", "Explore Categories", "Explorar categorías"),
    "deliveryCategorySupermarket": ("Supermercado", "Supermarket", "Supermercado"),
    "deliveryCategorySupermarketSubtitle": (
        "Essenciais frescos à sua porta",
        "Fresh essentials at your door",
        "Esenciales frescos a su puerta",
    ),
    "deliveryCategoryPharmacy": ("Farmácia", "Pharmacy", "Farmacia"),
    "deliveryCategoryBeverages": ("Bebidas", "Beverages", "Bebidas"),
    "deliveryCategoryHealth": ("Saúde & Bem-estar", "Health & Wellness", "Salud y bienestar"),
    "deliveryPartnersTitle": ("Parceiros Premium", "Premium Partners", "Socios Premium"),
    "deliveryPartnersSubtitle": (
        "Qualidade garantida e entregas rápidas",
        "Guaranteed quality and fast delivery",
        "Calidad garantizada y entregas rápidas",
    ),
    "deliveryHighlightsTitle": ("Destaques da Semana", "Weekly Highlights", "Destacados de la semana"),
    "discoverSummerHighlight": ("DESTAQUE DE VERÃO", "SUMMER HIGHLIGHT", "DESTACADO DE VERANO"),
    "discoverHeroTitle": ("A Essência do Mediterrâneo", "The Essence of the Mediterranean", "La esencia del Mediterráneo"),
    "discoverHeroSubtitle": (
        "Descubra refúgios secretos e experiências de luxo desenhadas para o viajante exigente.",
        "Discover secret retreats and luxury experiences designed for the discerning traveler.",
        "Descubra refugios secretos y experiencias de lujo diseñadas para el viajero exigente.",
    ),
    "discoverSearchHint": (
        "Procurar restaurantes, festas ou praias...",
        "Search restaurants, parties or beaches...",
        "Buscar restaurantes, fiestas o playas...",
    ),
    "discoverFilters": ("Filtros", "Filters", "Filtros"),
    "discoverExploreMap": ("Explorar Mapa", "Explore Map", "Explorar mapa"),
    "discoverExperiencesTitle": ("Experiências Exclusivas", "Exclusive Experiences", "Experiencias exclusivas"),
    "discoverCategoryGastronomy": ("Gastronomia", "Gastronomy", "Gastronomía"),
    "discoverExperienceRestaurants": ("Restaurantes de Autor", "Signature Restaurants", "Restaurantes de autor"),
    "discoverCategoryExploration": ("Exploração", "Exploration", "Exploración"),
    "discoverExperienceSecretSpots": ("Recantos Secretos", "Secret Spots", "Rincones secretos"),
    "discoverUpcomingEvents": ("Próximos Eventos", "Upcoming Events", "Próximos eventos"),
    "discoverTickets": ("Bilhetes", "Tickets", "Entradas"),
    "discoverInteractiveMapTitle": ("Mapa Interativo", "Interactive Map", "Mapa interactivo"),
    "discoverInteractiveMapSubtitle": (
        "Explore os pontos de interesse perto de si.",
        "Explore points of interest near you.",
        "Explore puntos de interés cerca de usted.",
    ),
    "discoverCurrentLocation": ("Localização Atual", "Current Location", "Ubicación actual"),
    "eventDateTimeLabel": ("Data e Hora", "Date & Time", "Fecha y hora"),
    "eventLocationLabel": ("Localização", "Location", "Ubicación"),
    "eventAboutTitle": ("Sobre o Evento", "About the Event", "Sobre el evento"),
    "eventDirectionsTitle": ("Como chegar", "How to get there", "Cómo llegar"),
    "eventOpenGps": ("Abrir no GPS", "Open in GPS", "Abrir en GPS"),
    "eventStandardTicket": ("Bilhete Normal", "Standard Ticket", "Entrada estándar"),
    "eventStandardTicketDesc": ("Acesso geral + 1 bebida", "General access + 1 drink", "Acceso general + 1 bebida"),
    "eventServiceFee": ("Taxa de Serviço", "Service Fee", "Tasa de servicio"),
    "eventPayNow": ("Pagar Agora", "Pay Now", "Pagar ahora"),
    "eventVipExperience": ("Experiência VIP", "VIP Experience", "Experiencia VIP"),
    "eventLimited": ("LIMITADO", "LIMITED", "LIMITADO"),
    "eventVipDescription": (
        "Mesa reservada, garrafa incluída e acesso ao backstage.",
        "Reserved table, bottle included and backstage access.",
        "Mesa reservada, botella incluida y acceso al backstage.",
    ),
    "eventCheckAvailability": ("Ver disponibilidade →", "Check availability →", "Ver disponibilidad →"),
    "jetskiAdventureTag": ("Aventura no Mar", "Sea Adventure", "Aventura en el mar"),
    "jetskiHeroTitle": ("Domine as Ondas", "Master the Waves", "Domine las olas"),
    "jetskiHeroSubtitle": (
        "Aluguer premium de motas de água de alta performance.",
        "Premium high-performance jet ski rental.",
        "Alquiler premium de motos de agua de alto rendimiento.",
    ),
    "jetskiDurationLabel": ("DURAÇÃO", "DURATION", "DURACIÓN"),
    "jetskiDurationValue": ("1 Hora — Passeio Rápido", "1 Hour — Quick Ride", "1 hora — Paseo rápido"),
    "jetskiExploreFleet": ("Explorar Frota", "Explore Fleet", "Explorar flota"),
    "jetskiOurFleet": ("Nossa Frota", "Our Fleet", "Nuestra flota"),
    "jetskiBookNow": ("Reservar Agora", "Book Now", "Reservar ahora"),
    "jetskiSafetyTitle": ("Segurança Primeiro", "Safety First", "Seguridad primero"),
    "jetskiSafetyLifeJacketTitle": ("Colete Salva-vidas Incluído", "Life Jacket Included", "Chaleco salvavidas incluido"),
    "jetskiSafetyLifeJacketSubtitle": (
        "Equipamento homologado para todos os pesos.",
        "Approved equipment for all weights.",
        "Equipo homologado para todos los pesos.",
    ),
    "jetskiSafetyBriefingTitle": ("Briefing de Segurança", "Safety Briefing", "Briefing de seguridad"),
    "jetskiSafetyBriefingSubtitle": (
        "Instrução obrigatória de 15 min antes da partida.",
        "Mandatory 15-min instruction before departure.",
        "Instrucción obligatoria de 15 min antes de la salida.",
    ),
    "jetskiSafetyGpsTitle": ("Monitorização GPS", "GPS Monitoring", "Monitorización GPS"),
    "jetskiSafetyGpsSubtitle": (
        "Equipa de apoio pronta para intervir 24/7.",
        "Support team ready to intervene 24/7.",
        "Equipo de apoyo listo para intervenir 24/7.",
    ),
    "jetskiOurBase": ("Nossa Base", "Our Base", "Nuestra base"),
    "jetskiOpenMap": ("Abrir Mapa", "Open Map", "Abrir mapa"),
    "premiumHomeSearchHint": (
        "Procure destino ou serviço...",
        "Search destination or service...",
        "Busque destino o servicio...",
    ),
    "premiumHomeNoResults": (
        "Nenhum resultado encontrado",
        "No results found",
        "No se encontraron resultados",
    ),
    "premiumHomeFastDelivery": ("Entregas Rápidas", "Fast Delivery", "Entregas rápidas"),
    "premiumHomeGroceryPharmacy": ("Mercearia e Farmácia", "Grocery & Pharmacy", "Comestibles y farmacia"),
    "premiumHomeIslandGuide": ("Guia de Ilhas", "Island Guide", "Guía de islas"),
    "premiumHomeJetski": ("Mota de Água", "Jet Ski", "Moto de agua"),
    "premiumHomeTransportTitle": ("Transporte e Mobilidade", "Transport & Mobility", "Transporte y movilidad"),
    "premiumHomeTransportTrip": ("Viagem", "Trip", "Viaje"),
    "premiumHomeTransportMoto": ("Moto", "Motorcycle", "Moto"),
    "premiumHomeTransportScooter": ("Trotinete", "Scooter", "Patinete"),
    "premiumHomeTransportBike": ("Bicicleta", "Bicycle", "Bicicleta"),
    "premiumHomeExperiencesTitle": ("Experiências Premium", "Premium Experiences", "Experiencias Premium"),
    "premiumHomeJetskiRentalTitle": ("Aluguer de Motas de Água", "Jet Ski Rental", "Alquiler de motos de agua"),
    "premiumHomeJetskiRentalDesc": (
        "Explore as águas cristalinas com o nosso novo serviço de aluguer premium.",
        "Explore crystal-clear waters with our new premium rental service.",
        "Explore aguas cristalinas con nuestro nuevo servicio de alquiler premium.",
    ),
    "premiumHomeFromPrice": ("Desde 45€", "From €45", "Desde 45€"),
    "premiumHomeIslandGuideTitle": ("Guia Exclusivo de Ilhas", "Exclusive Island Guide", "Guía exclusivo de islas"),
    "premiumHomeIslandGuideDesc": (
        "Descubra os segredos das ilhas com roteiros personalizados pelos locais.",
        "Discover island secrets with personalized local itineraries.",
        "Descubra los secretos de las islas con rutas personalizadas locales.",
    ),
    "rentalPickupLocation": ("Local de Recolha", "Pickup Location", "Lugar de recogida"),
    "rentalDropoffLocation": ("Local de Entrega", "Drop-off Location", "Lugar de entrega"),
    "rentalSamePickupHint": ("Mesmo local de recolha", "Same pickup location", "Mismo lugar de recogida"),
    "rentalDateSelection": ("Seleção de Datas", "Date Selection", "Selección de fechas"),
    "rentalDriverAge": ("Idade do Condutor", "Driver Age", "Edad del conductor"),
    "rentalDriverAgeNote": (
        "Taxas adicionais podem ser aplicadas para condutores fora do intervalo padrão.",
        "Additional fees may apply for drivers outside the standard range.",
        "Pueden aplicarse tarifas adicionales para conductores fuera del rango estándar.",
    ),
    "rentalPremiumOnly": ("Premium Only", "Premium Only", "Solo Premium"),
    "rentalLuxuryFleetOnly": (
        "Mostrar apenas frota de luxo",
        "Show luxury fleet only",
        "Mostrar solo flota de lujo",
    ),
    "rentalViewFleetOnMap": ("Ver frota no mapa", "View fleet on map", "Ver flota en el mapa"),
    "rentalCarType": ("Tipo de Carro", "Car Type", "Tipo de coche"),
    "rentalMaxPrice": ("Preço Máximo", "Max Price", "Precio máximo"),
    "rentalTransmission": ("Transmissão", "Transmission", "Transmisión"),
    "rentalFilter": ("Filtrar", "Filter", "Filtrar"),
    "rentalPremiumHighlights": ("Destaques Premium", "Premium Highlights", "Destacados Premium"),
    "rentalResultsFound": (
        "{count} resultados encontrados",
        "{count} results found",
        "{count} resultados encontrados",
    ),
    "rentalPremiumChoice": ("Premium Choice", "Premium Choice", "Elección Premium"),
    "rentalAllCars": ("Todos os Carros", "All Cars", "Todos los coches"),
    "rentalLoadMore": ("Carregar mais veículos", "Load more vehicles", "Cargar más vehículos"),
    "rentalVehicleDetails": ("Detalhes do Veículo", "Vehicle Details", "Detalles del vehículo"),
    "rentalRating": ("Classificação", "Rating", "Calificación"),
    "rentalPowertrain": ("Motorização", "Powertrain", "Motorización"),
    "rentalCapacity": ("Capacidade", "Capacity", "Capacidad"),
    "rentalAcceleration": ("Aceleração", "Acceleration", "Aceleración"),
    "rentalInsuranceIncluded": ("Seguro Incluído", "Insurance Included", "Seguro incluido"),
    "rentalFuelPolicy": ("Combustível", "Fuel", "Combustible"),
    "rentalCurrentBattery": ("Bateria Atual", "Current Battery", "Batería actual"),
    "rentalBookingSummary": ("Resumo da Reserva", "Booking Summary", "Resumen de la reserva"),
    "rentalTotalCost": ("Custo Total", "Total Cost", "Costo total"),
    "rentalTechnicalSpecs": ("ESPECIFICAÇÕES TÉCNICAS", "TECHNICAL SPECIFICATIONS", "ESPECIFICACIONES TÉCNICAS"),
    "rentalReservationTotal": ("Total da reserva", "Reservation total", "Total de la reserva"),
    "rentalContinueToPayment": ("Continuar para Pagamento", "Continue to Payment", "Continuar al pago"),
    "rentalPerDay": ("/dia", "/day", "/día"),
    "rentalSeats": ("{count} Lugares", "{count} Seats", "{count} plazas"),
    "rentalBag": ("Mala", "Bag", "Maleta"),
    "rentalBags": ("Malas", "Bags", "Maletas"),
    "reservationReviewTitle": ("Revisão da Reserva", "Reservation Review", "Revisión de la reserva"),
    "reservationItinerary": ("Itinerário", "Itinerary", "Itinerario"),
    "reservationPickupLabel": ("LEVANTAMENTO", "PICKUP", "RECOGIDA"),
    "reservationReturnLabel": ("DEVOLUÇÃO", "RETURN", "DEVOLUCIÓN"),
    "reservationSecurePayment": ("Pagamento 100% Seguro", "100% Secure Payment", "Pago 100% seguro"),
    "reservationSecurePaymentDesc": (
        "Utilizamos encriptação SSL de 256 bits para proteger os seus dados.",
        "We use 256-bit SSL encryption to protect your data.",
        "Usamos cifrado SSL de 256 bits para proteger sus datos.",
    ),
    "reservationCostSummary": ("Resumo de Custos", "Cost Summary", "Resumen de costes"),
    "reservationNoHiddenFees": ("Sem custos ocultos", "No hidden fees", "Sin costes ocultos"),
    "reservationPaymentMethod": ("Método de Pagamento", "Payment Method", "Método de pago"),
    "reservationCreditCard": ("Cartão de Crédito", "Credit Card", "Tarjeta de crédito"),
    "reservationPayWithApplePay": ("Pagar com Apple Pay", "Pay with Apple Pay", "Pagar con Apple Pay"),
    "reservationConfirmAndPay": ("Confirmar e Pagar", "Confirm and Pay", "Confirmar y pagar"),
    "reservationTermsPrefix": (
        'Ao clicar em "Confirmar e Pagar", aceita os nossos ',
        'By clicking "Confirm and Pay", you accept our ',
        'Al hacer clic en "Confirmar y pagar", acepta nuestros ',
    ),
    "reservationTermsLink": ("Termos e Condições", "Terms and Conditions", "Términos y condiciones"),
    "reservationFullInsurance": ("Seguro Total Incluído", "Full Insurance Included", "Seguro total incluido"),
    "reservationsEmptyTitle": (
        "Ainda não tem mais reservas",
        "You have no more reservations yet",
        "Aún no tiene más reservas",
    ),
    "reservationsEmptyBody": (
        "Planeie a sua próxima viagem com a nossa frota premium. Conforto e pontualidade garantidos.",
        "Plan your next trip with our premium fleet. Comfort and punctuality guaranteed.",
        "Planifique su próximo viaje con nuestra flota premium. Confort y puntualidad garantizados.",
    ),
    "reservationsExploreDestinations": ("Explorar destinos", "Explore destinations", "Explorar destinos"),
    "tripHistoryActivity": ("A Minha Atividade", "My Activity", "Mi actividad"),
    "tripHistoryTrips": ("Viagens", "Trips", "Viajes"),
    "tripHistoryThisMonth": ("Este Mês", "This Month", "Este mes"),
    "tripHistoryFilterAll": ("Todos", "All", "Todos"),
    "tripHistoryFilterRecent": ("Viagens Recentes", "Recent Trips", "Viajes recientes"),
    "tripHistoryFilterCompleted": ("Concluídas", "Completed", "Completadas"),
    "tripHistoryFilterCancelled": ("Canceladas", "Cancelled", "Canceladas"),
    "tripHistoryFilterThisYear": ("Este Ano", "This Year", "Este año"),
    "tripHistoryStatusCancelled": ("Cancelada", "Cancelled", "Cancelada"),
    "tripHistoryNoDetails": ("Sem detalhes", "No details", "Sin detalles"),
    "tripDetailsRateExperience": ("Avalie a sua experiência", "Rate your experience", "Valore su experiencia"),
    "tripDetailsDigitalInvoice": ("Fatura Digital", "Digital Invoice", "Factura digital"),
    "tripDetailsTotalPaid": ("Total Pago", "Total Paid", "Total pagado"),
    "tripDetailsMethod": ("Método", "Method", "Método"),
    "tripDetailsDownloadPdf": ("Descarregar PDF", "Download PDF", "Descargar PDF"),
    "tripDetailsFareBase": ("Tarifa Base", "Base Fare", "Tarifa base"),
    "tripDetailsFareDistance": ("Distância (12.5 km)", "Distance (12.5 km)", "Distancia (12.5 km)"),
    "tripDetailsFareTime": ("Tempo (24 min)", "Time (24 min)", "Tiempo (24 min)"),
    "tripDetailsFareDiscount": ("Desconto Promocional", "Promotional Discount", "Descuento promocional"),
    "tripDetailsSupportTitle": ("Algo correu mal?", "Something went wrong?", "¿Algo salió mal?"),
    "tripDetailsSupportLostItem": ("Reportar objeto perdido", "Report lost item", "Reportar objeto perdido"),
    "tripDetailsSupportSafety": ("Reclamação de segurança", "Safety complaint", "Reclamación de seguridad"),
    "tripDetailsSupportCustomer": ("Apoio ao cliente", "Customer support", "Atención al cliente"),
    "tripCompletedThanks": (
        "Obrigado por viajar connosco.",
        "Thank you for riding with us.",
        "Gracias por viajar con nosotros.",
    ),
    "tripCompletedFinalPrice": ("Preço Final", "Final Price", "Precio final"),
    "tripCompletedOptimizedRoute": ("Trajeto otimizado", "Optimized route", "Trayecto optimizado"),
    "tripCompletedRateTrip": ("Avalie a Viagem", "Rate the Trip", "Valore el viaje"),
    "tripCompletedRateHint": (
        "Como correu a sua experiência com o motorista e o veículo?",
        "How was your experience with the driver and vehicle?",
        "¿Cómo fue su experiencia con el conductor y el vehículo?",
    ),
    "tripCompletedCommentOptional": ("Comentário (opcional)", "Comment (optional)", "Comentario (opcional)"),
    "tripCompletedCommentHint": ("Partilhe a sua opinião...", "Share your opinion...", "Comparta su opinión..."),
    "tripCompletedSubmitRating": ("Enviar avaliação", "Submit rating", "Enviar valoración"),
    "tripCompletedRatingSent": ("Avaliação enviada", "Rating submitted", "Valoración enviada"),
    "tripCompletedReportIssue": ("Reportar problema", "Report issue", "Reportar problema"),
    "tripInProgressStatusLabel": ("Status da Viagem", "Trip Status", "Estado del viaje"),
    "tripInProgressStatusValue": ("Em viagem", "In progress", "En curso"),
    "tripInProgressArrivalLabel": ("Chegada prevista", "Estimated arrival", "Llegada prevista"),
    "tripInProgressCostLabel": ("Custo Estimado", "Estimated Cost", "Costo estimado"),
    "driverSearchSubtitle": (
        "Estamos a ligar-te aos veículos mais próximos em Lisboa Central.",
        "Connecting you to the nearest vehicles in Central Lisbon.",
        "Conectándole con los vehículos más cercanos en Lisboa Central.",
    ),
    "driverSearchOrigin": ("ORIGEM", "ORIGIN", "ORIGEN"),
    "driverSearchEstimate": ("ESTIMATIVA", "ESTIMATE", "ESTIMACIÓN"),
    "driverSearchCancelTrip": ("Cancelar Viagem", "Cancel Trip", "Cancelar viaje"),
    "driverSearchOptimizing": (
        "Otimizando percurso em tempo real...",
        "Optimizing route in real time...",
        "Optimizando ruta en tiempo real...",
    ),
    "driverFoundWaiting": (
        "A aguardar confirmação...",
        "Awaiting confirmation...",
        "Esperando confirmación...",
    ),
    "driverFoundEstimatedTime": ("Tempo estimado", "Estimated time", "Tiempo estimado"),
    "driverFoundFare": ("Tarifa", "Fare", "Tarifa"),
    "driverFoundCancelHint": (
        "Pode cancelar sem custos nos próximos 2 minutos enquanto o motorista confirma a reserva.",
        "You can cancel free of charge within the next 2 minutes while the driver confirms the booking.",
        "Puede cancelar sin coste en los próximos 2 minutos mientras el conductor confirma la reserva.",
    ),
    "driverEnRouteYourLocation": ("A sua localização", "Your location", "Su ubicación"),
    "driverEnRouteMessage": ("Mensagem", "Message", "Mensaje"),
    "driverEnRouteCall": ("Ligar", "Call", "Llamar"),
    "tripDestinationSubtitle": (
        "Procure um destino ou escolha um dos seus locais frequentes.",
        "Search for a destination or choose one of your frequent places.",
        "Busque un destino o elija uno de sus lugares frecuentes.",
    ),
    "tripDestinationSearchHint": (
        "Pesquisar endereço ou ponto de interesse",
        "Search address or point of interest",
        "Buscar dirección o punto de interés",
    ),
    "tripDestinationRecentPlaces": ("Locais Recentes", "Recent Places", "Lugares recientes"),
    "tripDestinationSuggestions": ("Sugestões e Favoritos", "Suggestions & Favorites", "Sugerencias y favoritos"),
    "tripDestinationExploreMap": ("Explorar Mapa", "Explore Map", "Explorar mapa"),
    "tripDestinationTodaySuggestion": ("SUGESTÃO DE HOJE", "TODAY'S SUGGESTION", "SUGERENCIA DE HOY"),
    "tripDestinationViewFullMap": ("Ver Mapa Completo", "View Full Map", "Ver mapa completo"),
    "tripConfirmTransportType": ("Tipo de Transporte", "Transport Type", "Tipo de transporte"),
    "tripConfirmTotal": ("Total: {amount}", "Total: {amount}", "Total: {amount}"),
    "tripConfirmTrip": ("Confirmar viagem", "Confirm trip", "Confirmar viaje"),
    "tripConfirmPickupPoint": ("PONTO DE RECOLHA", "PICKUP POINT", "PUNTO DE RECOGIDA"),
    "tripConfirmFinalDestination": ("DESTINO FINAL", "FINAL DESTINATION", "DESTINO FINAL"),
    "tripConfirmTransportPremium": ("Premium", "Premium", "Premium"),
    "tripConfirmTransportEco": ("Eco-Eletric", "Eco-Electric", "Eco-Eléctrico"),
    "tripConfirmTransportShared": ("Partilhado", "Shared", "Compartido"),
}


def build_locale(locale_code: str, index: int) -> dict:
    data = {"@@locale": locale_code}
    for key, values in strings.items():
        data[key] = values[index]
        if "{" in values[index]:
            placeholders = {name: {"type": "String"} for name in re.findall(r"\{(\w+)\}", values[index])}
            data[f"@{key}"] = {"placeholders": placeholders}
    return data


base = Path(__file__).resolve().parent.parent / "lib" / "l10n"
base.mkdir(parents=True, exist_ok=True)
for filename, locale, idx in [
    ("app_pt.arb", "pt", 0),
    ("app_en.arb", "en", 1),
    ("app_es.arb", "es", 2),
]:
    path = base / filename
    path.write_text(json.dumps(build_locale(locale, idx), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {path.name}")
